'use client';

import Link from 'next/link';
import { ArrowRight, CheckCircle2, Truck } from 'lucide-react';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { PageTitle, StatusBadge } from '@/components/support-panel/support-shell';
import { supportGet, supportPatch } from '@/lib/support-api';

type Order = { id: string; orderNumber: string; customerName: string; customerPhone: string; customerEmail?: string; shippingAddress: string; total: string | number; status: string; trackingCode?: string; items: Array<{ id: string; productName: string; quantity: number; lineTotal: string | number }> };
export default function OrderDetailPage() { const { id } = useParams<{ id: string }>(); const [order, setOrder] = useState<Order | null>(null); const [tracking, setTracking] = useState(''); const [status, setStatus] = useState(''); const load = () => supportGet<Order>(`/support/orders/${id}`).then((value) => { setOrder(value); setTracking(value.trackingCode ?? ''); setStatus(value.status); }).catch(() => {}); useEffect(load, [id]); async function saveTracking() { await supportPatch(`/support/orders/${id}/tracking`, { trackingCode: tracking, notifyCustomer: true }); load(); } async function saveStatus() { await supportPatch(`/support/orders/${id}/status`, { status, notifyCustomer: true }); load(); } return <section className="support-page"><Link href="/support-panel/orders" className="support-back"><ArrowRight size={16} /> بازگشت به سفارش‌ها</Link><PageTitle title={order?.orderNumber ?? 'جزئیات سفارش'} description={order ? `${order.customerName} · ${order.customerPhone}` : ''} action={order && <StatusBadge value={order.status} />} />{order && <div className="support-detail"><div className="support-card"><h3>اقلام سفارش</h3><div className="support-list">{order.items.map((item) => <div className="support-list-item" key={item.id}><div><strong>{item.productName}</strong><small>تعداد: {item.quantity}</small></div><strong>{Number(item.lineTotal).toLocaleString('fa-IR')} ریال</strong></div>)}</div><div className="support-card" style={{ marginTop: 16, padding: 16, background: '#f8fbfe' }}><strong>مبلغ نهایی: {Number(order.total).toLocaleString('fa-IR')} ریال</strong></div></div><div className="support-card"><h3>ارسال و رهگیری</h3><div className="support-form"><label>کد رهگیری</label><input className="support-input" value={tracking} onChange={(e) => setTracking(e.target.value)} placeholder="کد رهگیری مرسوله" /><button className="support-button" onClick={saveTracking}><Truck size={16} /> ثبت کد رهگیری</button><label style={{ marginTop: 12 }}>وضعیت سفارش</label><select className="support-select" value={status} onChange={(e) => setStatus(e.target.value)}><option value="pending">در انتظار</option><option value="processing">در حال پردازش</option><option value="shipped">ارسال شده</option><option value="delivered">تحویل شده</option><option value="cancelled">لغو شده</option></select><button className="support-button secondary" onClick={saveStatus}><CheckCircle2 size={16} /> ذخیره وضعیت</button></div><h3 style={{ marginTop: 28 }}>آدرس ارسال</h3><p style={{ color: '#587087', lineHeight: 1.9 }}>{order.shippingAddress || 'ثبت نشده'}</p></div></div>}</section>; }
