'use client';

import Link from 'next/link';
import { ArrowLeft, Package } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageTitle, StatusBadge } from '@/components/support-panel/support-shell';
import { supportGet } from '@/lib/support-api';

type Order = { id: string; orderNumber: string; customerName: string; customerPhone: string; total: string | number; status: string; trackingCode?: string; createdAt: string };
export default function OrdersPage() { const [rows, setRows] = useState<Order[]>([]); const [status, setStatus] = useState('all'); useEffect(() => { supportGet<Order[]>(`/support/orders${status === 'all' ? '' : `?status=${status}`}`).then(setRows).catch(() => setRows([])); }, [status]); return <section className="support-page"><PageTitle eyebrow="ماژول سفارش‌ها" title="مدیریت سفارش‌های فروشگاه" description="رهگیری و وضعیت ارسال سفارش‌های مشتریان را کنترل کنید." /><div className="support-card"><div className="support-filters"><select className="support-select" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">همه وضعیت‌ها</option><option value="pending">در انتظار</option><option value="processing">در حال پردازش</option><option value="shipped">ارسال شده</option><option value="delivered">تحویل شده</option><option value="cancelled">لغو شده</option></select></div><div className="support-table-wrap"><table className="support-table"><thead><tr><th>شماره سفارش</th><th>مشتری</th><th>مبلغ</th><th>وضعیت</th><th>کد رهگیری</th><th>تاریخ</th><th>عملیات</th></tr></thead><tbody>{rows.map((order) => <tr key={order.id}><td>{order.orderNumber}</td><td>{order.customerName}<small>{order.customerPhone}</small></td><td>{Number(order.total).toLocaleString('fa-IR')} ریال</td><td><StatusBadge value={order.status} /></td><td>{order.trackingCode ?? 'ثبت نشده'}</td><td>{new Date(order.createdAt).toLocaleDateString('fa-IR')}</td><td><Link href={`/support-panel/orders/${order.id}`} className="support-button secondary"><ArrowLeft size={15} /> جزئیات</Link></td></tr>)}</tbody></table>{!rows.length && <div className="support-empty"><Package size={30} /> سفارشی یافت نشد</div>}</div></div></section>; }
