'use client';

import Link from 'next/link';
import { Activity, Clock3, MessageCircle, Package, Star, Ticket } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageTitle, StatusBadge } from '@/components/support-panel/support-shell';
import { supportGet } from '@/lib/support-api';

type Summary = { tickets: Array<{ id: string; subject: string; priority: string; status: string; createdAt: string }>; chats: Array<{ id: string; status: string; user?: { fullName: string } }>; telereports: Array<{ id: string; status: string }>; reviews: Array<{ id: string; status: string }>; orders: Array<{ id: string; status: string }> };

export default function SupportDashboard() {
  const [data, setData] = useState<Summary | null>(null);
  useEffect(() => { Promise.all([supportGet<Summary['tickets']>('/support/tickets?priority=urgent&limit=5'), supportGet<Summary['chats']>('/support/chats'), supportGet<Summary['telereports']>('/support/telereports?status=pending'), supportGet<Summary['reviews']>('/support/reviews'), supportGet<Summary['orders']>('/support/orders?status=pending')]).then(([tickets, chats, telereports, reviews, orders]) => setData({ tickets: Array.isArray(tickets) ? tickets : (tickets as { items: Summary['tickets'] }).items ?? [], chats: chats ?? [], telereports: telereports ?? [], reviews: reviews ?? [], orders: orders ?? [] })).catch(() => setData({ tickets: [], chats: [], telereports: [], reviews: [], orders: [] })); }, []);
  const stats = [{ label: 'تیکت‌های باز', value: data?.tickets.length ?? '—', icon: Ticket }, { label: 'چت‌های در انتظار', value: data?.chats.filter((x) => x.status === 'waiting').length ?? '—', icon: MessageCircle }, { label: 'تله‌ریپورت‌های pending', value: data?.telereports.length ?? '—', icon: Activity }, { label: 'نظرات در انتظار', value: data?.reviews.length ?? '—', icon: Star }];
  return <section className="support-page"><PageTitle eyebrow="نمای کلی عملکرد" title="سلام، {کارشناس پشتیبانی}" description="وضعیت امروز مرکز پشتیبانی را در یک نگاه ببینید." /><div className="support-grid">{stats.map(({ label, value, icon: Icon }) => <div className="support-stat" key={label}><div className="support-stat-icon"><Icon size={21} /></div><div><span>{label}</span><strong>{value}</strong></div></div>)}</div><div className="support-dashboard-columns"><div className="support-card"><div className="support-card-heading"><h3>تیکت‌های اولویت بالا</h3><Link href="/support-panel/tickets">مشاهده همه</Link></div><div className="support-list">{data?.tickets.length ? data.tickets.map((ticket) => <Link href={`/support-panel/tickets/${ticket.id}`} className="support-list-item" key={ticket.id}><div><strong>{ticket.subject}</strong><small><Clock3 size={12} /> {new Date(ticket.createdAt).toLocaleDateString('fa-IR')}</small></div><StatusBadge value={ticket.priority} /></Link>) : <div className="support-empty">تیکت فوری وجود ندارد</div>}</div></div><div className="support-card"><div className="support-card-heading"><h3>سفارش‌های نیازمند پیگیری</h3><Link href="/support-panel/orders">مشاهده همه</Link></div><div className="support-list">{data?.orders.length ? data.orders.slice(0, 5).map((order) => <Link href={`/support-panel/orders/${order.id}`} className="support-list-item" key={order.id}><div><strong>سفارش {order.id.slice(0, 8)}</strong><small>ثبت شده در فروشگاه</small></div><StatusBadge value={order.status} /></Link>) : <div className="support-empty">سفارشی برای پیگیری وجود ندارد</div>}</div></div></div><div className="support-card" style={{ marginTop: 18 }}><div className="support-card-heading"><h3>دسترسی سریع</h3></div><div className="support-grid"><Link className="support-button secondary" href="/support-panel/tickets"><Ticket size={17} /> مدیریت تیکت‌ها</Link><Link className="support-button secondary" href="/support-panel/chat"><MessageCircle size={17} /> ورود به چت آنلاین</Link><Link className="support-button secondary" href="/support-panel/telereports"><Activity size={17} /> بررسی تله‌ریپورت‌ها</Link><Link className="support-button secondary" href="/support-panel/orders"><Package size={17} /> سفارش‌های فروشگاه</Link></div></div></section>;
}
