'use client';

import { Check, Star, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageTitle, StatusBadge } from '@/components/support-panel/support-shell';
import { supportGet, supportPatch } from '@/lib/support-api';

type Review = { id: string; content: string; rating: number; status: string; rejectReason?: string; createdAt: string; user?: { fullName: string; email: string } };
export default function ReviewsPage() { const [rows, setRows] = useState<Review[]>([]); const [status, setStatus] = useState('pending'); const [rejecting, setRejecting] = useState<string | null>(null); const [reason, setReason] = useState(''); const load = () => supportGet<Review[]>(`/support/reviews/all?status=${status}`).then(setRows).catch(() => setRows([])); useEffect(load, [status]); async function approve(id: string) { await supportPatch(`/support/reviews/${id}/approve`); load(); } async function reject(id: string) { await supportPatch(`/support/reviews/${id}/reject`, { reason }); setRejecting(null); setReason(''); load(); } return <section className="support-page"><PageTitle eyebrow="مدیریت بازخورد" title="نظرات کاربران" description="نظرات را بررسی، تأیید یا با ذکر دلیل رد کنید." /><div className="support-filters"><button className={`support-button ${status === 'pending' ? '' : 'secondary'}`} onClick={() => setStatus('pending')}>در انتظار تأیید</button><button className={`support-button ${status === 'approved' ? '' : 'secondary'}`} onClick={() => setStatus('approved')}>تأیید شده</button><button className={`support-button ${status === 'rejected' ? '' : 'secondary'}`} onClick={() => setStatus('rejected')}>رد شده</button></div><div className="support-list">{rows.map((review) => <div className="support-card" key={review.id}><div className="support-card-heading"><div><h3>{review.user?.fullName ?? 'کاربر'}</h3><small>{new Date(review.createdAt).toLocaleDateString('fa-IR')} · {review.user?.email}</small></div><StatusBadge value={review.status} /></div><div className="support-rating">{'★'.repeat(Math.max(0, Math.min(review.rating, 5)))}<span style={{ color: '#7890a7', marginRight: 8 }}>{review.rating}/5</span></div><p style={{ color: '#506984', lineHeight: 1.9 }}>{review.content}</p>{review.rejectReason && <p style={{ color: '#c75a5a' }}>دلیل رد: {review.rejectReason}</p>}{review.status === 'pending' && <div className="support-form-actions"><button className="support-button" onClick={() => approve(review.id)}><Check size={16} /> تأیید نظر</button><button className="support-button danger" onClick={() => setRejecting(review.id)}><X size={16} /> رد نظر</button></div>}{rejecting === review.id && <div className="support-form" style={{ marginTop: 15 }}><textarea className="support-textarea" placeholder="دلیل رد نظر" value={reason} onChange={(e) => setReason(e.target.value)} /><div className="support-form-actions"><button className="support-button danger" onClick={() => reject(review.id)}>ثبت رد</button><button className="support-button secondary" onClick={() => setRejecting(null)}>انصراف</button></div></div>}</div>)}{!rows.length && <div className="support-card support-empty"><Star size={30} /> نظری برای نمایش وجود ندارد</div>}</div></section>; }
