'use client';

import Link from 'next/link';
import { Search, Ticket } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageTitle, StatusBadge } from '@/components/support-panel/support-shell';
import { supportGet } from '@/lib/support-api';

type TicketRow = { id: string; subject: string; message: string; status: string; priority: string; createdAt: string; user?: { fullName: string; email: string }; expert?: { fullName: string } };
type Result = { items: TicketRow[]; total: number };
export default function TicketsPage() { const [rows, setRows] = useState<TicketRow[]>([]); const [status, setStatus] = useState('all'); const [priority, setPriority] = useState('all'); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const load = () => { const query = new URLSearchParams({ ...(status !== 'all' ? { status } : {}), ...(priority !== 'all' ? { priority } : {}), ...(search ? { search } : {}) }); supportGet<Result>(`/support/tickets?${query}`).then((data) => setRows(data.items ?? [])).catch((e: Error) => setError(e.message)); }; useEffect(load, [status, priority]); return <section className="support-page"><PageTitle eyebrow="ماژول تیکت‌ها" title="مدیریت تیکت‌ها" description="تمام درخواست‌های کاربران را بررسی و پاسخ دهید." action={<button className="support-button" onClick={load}><Search size={16} /> جستجو</button>} /><div className="support-card"><div className="support-filters"><input className="support-input" placeholder="جستجو در موضوع یا کاربر" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="support-select" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">همه وضعیت‌ها</option><option value="open">باز</option><option value="pending">در انتظار</option><option value="closed">بسته</option></select><select className="support-select" value={priority} onChange={(e) => setPriority(e.target.value)}><option value="all">همه اولویت‌ها</option><option value="urgent">فوری</option><option value="high">زیاد</option><option value="medium">متوسط</option><option value="low">کم</option></select></div>{error ? <div className="support-error">{error}</div> : <div className="support-table-wrap"><table className="support-table"><thead><tr><th>موضوع</th><th>کاربر</th><th>اولویت</th><th>وضعیت</th><th>کارشناس</th><th>عملیات</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.subject}</strong><small>{new Date(row.createdAt).toLocaleDateString('fa-IR')}</small></td><td>{row.user?.fullName ?? '—'}</td><td><StatusBadge value={row.priority} /></td><td><StatusBadge value={row.status} /></td><td>{row.expert?.fullName ?? 'اختصاص داده نشده'}</td><td><Link className="support-button secondary" href={`/support-panel/tickets/${row.id}`}>مشاهده</Link></td></tr>)}</tbody></table>{!rows.length && <div className="support-empty"><Ticket size={30} /> تیکتی برای نمایش وجود ندارد</div>}</div>}</div></section>; }
