'use client';

import { MessageCircle, Send, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageTitle, StatusBadge } from '@/components/support-panel/support-shell';
import { supportGet, supportPatch, supportPost } from '@/lib/support-api';

type Chat = { id: string; status: string; subject: string; user?: { fullName: string; email: string }; messages: Array<{ content: string; createdAt: string; sender?: { fullName: string; role: string } }> };
export default function ChatPage() { const [chats, setChats] = useState<Chat[]>([]); const [selected, setSelected] = useState<Chat | null>(null); const [text, setText] = useState(''); const load = () => supportGet<Chat[]>('/support/chats').then(setChats).catch(() => setChats([])); useEffect(() => { load(); const timer = window.setInterval(load, 15000); return () => window.clearInterval(timer); }, []); useEffect(() => { if (selected) supportGet<Chat>(`/support/chats/${selected.id}`).then(setSelected).catch(() => {}); }, [selected?.id]); async function send() { if (!selected || !text.trim()) return; await supportPost(`/support/chats/${selected.id}/messages`, { content: text }); setText(''); const detail = await supportGet<Chat>(`/support/chats/${selected.id}`); setSelected(detail); } async function close() { if (!selected) return; await supportPatch(`/support/chats/${selected.id}/close`); load(); setSelected(null); } return <section className="support-page"><PageTitle eyebrow="ارتباط لحظه‌ای" title="چت آنلاین" description="گفتگوهای فعال و در انتظار را مدیریت کنید." /><div className="support-chat-layout"><div className="support-card support-chat-list"><div className="support-card-heading"><h3>گفتگوها</h3><StatusBadge value="active" /></div>{chats.map((chat) => <button className={`support-chat-item ${selected?.id === chat.id ? 'active' : ''}`} key={chat.id} onClick={() => setSelected(chat)}><strong>{chat.user?.fullName ?? 'کاربر'}</strong><small>{chat.messages?.[0]?.content ?? 'پیام جدید'}</small><StatusBadge value={chat.status} /></button>)}{!chats.length && <div className="support-empty">گفتگوی فعالی وجود ندارد</div>}</div><div className="support-card support-chat-window">{selected ? <><div className="support-card-heading"><div><h3>{selected.user?.fullName ?? 'کاربر'}</h3><small>{selected.user?.email}</small></div><button className="support-button danger" onClick={close}><X size={16} /> بستن چت</button></div><div className="support-chat-messages">{selected.messages?.map((message, index) => <div key={`${message.createdAt}-${index}`} className={`support-chat-bubble ${message.sender?.role?.toLowerCase().includes('support') ? 'mine' : ''}`}><p>{message.content}</p><small>{message.sender?.fullName} · {new Date(message.createdAt).toLocaleTimeString('fa-IR', { hour: '2-digit', minute: '2-digit' })}</small></div>)}</div><div className="support-chat-compose"><input className="support-input" placeholder="پیام خود را بنویسید..." value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} /><button className="support-button" onClick={send}><Send size={16} /> ارسال</button></div></> : <div className="support-empty"><MessageCircle size={38} /> یک گفتگو را انتخاب کنید</div>}</div></div></section>; }
