'use client';

import Link from 'next/link';
import { ArrowRight, Send, XCircle } from 'lucide-react';
import { useParams, useRouter } from 'next/navigation';
import { FormEvent, useEffect, useState } from 'react';
import { PageTitle, StatusBadge } from '@/components/support-panel/support-shell';
import { supportGet, supportPatch, supportPost } from '@/lib/support-api';

type Detail = { id: string; subject: string; message: string; status: string; priority: string; createdAt: string; user?: { fullName: string; email: string }; replies: Array<{ id: string; message: string; createdAt: string; author?: { fullName: string; role: string } }> };
export default function TicketDetailPage() { const params = useParams<{ id: string }>(); const router = useRouter(); const [ticket, setTicket] = useState<Detail | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const load = () => supportGet<Detail>(`/support/tickets/${params.id}`).then(setTicket).catch((e: Error) => setError(e.message)); useEffect(load, [params.id]); async function reply(e: FormEvent) { e.preventDefault(); if (!message.trim()) return; await supportPost(`/support/tickets/${params.id}/reply`, { message }); setMessage(''); load(); } async function close() { await supportPatch(`/support/tickets/${params.id}/close`); load(); } return <section className="support-page"><Link href="/support-panel/tickets" className="support-back"><ArrowRight size={16} /> بازگشت به تیکت‌ها</Link><PageTitle title={ticket?.subject ?? 'جزئیات تیکت'} description={ticket?.user ? `${ticket.user.fullName} · ${ticket.user.email}` : ''} action={ticket && <div className="support-form-actions"><StatusBadge value={ticket.priority} /><StatusBadge value={ticket.status} /></div>} />{error ? <div className="support-error">{error}</div> : ticket && <div className="support-detail"><div className="support-card"><h3>رشته مکالمه</h3><div className="support-thread"><div className="support-message"><p>{ticket.message}</p><small>{ticket.user?.fullName} · {new Date(ticket.createdAt).toLocaleString('fa-IR')}</small></div>{ticket.replies.map((reply) => <div className={`support-message ${reply.author?.role?.toLowerCase().includes('support') ? 'expert' : ''}`} key={reply.id}><p>{reply.message}</p><small>{reply.author?.fullName} · {new Date(reply.createdAt).toLocaleString('fa-IR')}</small></div>)}</div><form className="support-form" onSubmit={reply} style={{ marginTop: 22 }}><textarea className="support-textarea" placeholder="پاسخ خود را بنویسید..." value={message} onChange={(e) => setMessage(e.target.value)} /><div className="support-form-actions"><button className="support-button" type="submit"><Send size={16} /> ارسال پاسخ</button><button className="support-button danger" type="button" onClick={close}><XCircle size={16} /> بستن تیکت</button></div></form></div><div className="support-card"><h3>اطلاعات تیکت</h3><div className="support-timeline"><div className="support-timeline-item"><i /><span>اولویت: <StatusBadge value={ticket.priority} /></span></div><div className="support-timeline-item"><i /><span>وضعیت: <StatusBadge value={ticket.status} /></span></div><div className="support-timeline-item"><i /><span>ثبت: {new Date(ticket.createdAt).toLocaleString('fa-IR')}</span></div></div></div></div>}</section>; }
